drop table if exists USERS CASCADE;
drop table if exists ITEMS CASCADE;
drop table if exists BOOKINGS CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR(255)                                  NOT NULL,
    email VARCHAR(512)                                 NOT NULL

);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name        varchar(255) UNIQUE,
    description varchar(255),
    available   boolean,
    owner       integer,
    request     integer
);

CREATE TABLE IF NOT EXISTS bookings
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    start  timestamp not null,
    finish    timestamp not null,
    item   integer   not null,
    booker integer   not null,
    status integer   not null
);